export const MENU_CHANGE ="MENU_CHANGE"
export const MESSAGES_CHANGE ="MESSAGES_CHANGE"
export const CHATWITH_SET ="CHATWITH_SET"
export const POST_REQUEST ="POST_REQUEST"
export const POST_SUCCESS ="POST_SUCCESS"
export const POST_FAIL ="POST_FAIL"
export const POST_SET = "POST_SET"

export const PROFILE_REQUEST ="PROFILE_REQUEST"
export const PROFILE_SUCCESS ="PROFILE_SUCCESS"
export const PROFILE_FAIL ="PROFILE_FAIL"
export const PROFILE_SET ="PROFILE_SET"


export const ADD_MESSAGE_REQUEST ="ADD_MESSAGE_REQUEST"
export const ADD_MESSAGE_SUCCESS ="ADD_MESSAGE_SUCCESS"
export const ADD_MESSAGE_FAIL ="ADD_MESSAGE_FAIL"
